### ISSUE TITLE
Sync master Dolibarr user database with linux account (module syncuser)

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#10]
The module must add a tab to allow a dolibarr user to  publish several ssh keys.
then module may also bring a script installed into dolibarr jobs, to create or disable unix account, database account, on server.
Goal is to manage easily addition/removal of a new board member and also be sure linux account on foundation server always match what we had setup in dolibarr.

**Comment by eldy** [comment]
Idea on how to implement this (other ideas are welcome):

The module must
- have a trigger on user disable or creation action to save a job entry into the table of dolibarr scheduled jobs, with maxrun=1, autodelete=2, status=1 and command =
  "usermod --lock --expiredate 1970-01-01 <username>"    to lock
  this opposite linux command to unlock
- the master cron job will run on server launched by unix cron by root user, so commands should succeed.

A similar command/script could be found and added to jobs for mysql account creation/delection

**Comment by jfefe** [comment]
We could use LDAP directory to store users information. It would be used into others tools such as mainling list or websites.
