### ISSUE TITLE
Close all bugs into our old system doliforge

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#13]
Close all bugs into our old system doliforge
- fixing bug and sending PR
- or just copy ticket github issue tracker

Goal is to close/delete the bug tracker on doliforge.

**Comment by rdoursenaud** [comment]
I can cook a migration script if someone has the Tuleap webservice API documentation.
@jfefe maybe?

**Comment by hregis** [comment]
@rdoursenaud  https://www.doliforge.org/soap/index.php

**Comment by eldy** [comment]
Abandonned. Doliforge will be closed. Old bugs would have to be entered in new system.
