### ISSUE TITLE
On dolistore, the description short must be limited to 400

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#14]
This is the limit in backoffice. We must share the same when using the dolistore module manager.
@hregis What do you think of just adding a maxsize into the textarea ?

**Comment by hregis** [comment]
@eldy yes the old system was not working, I'll look at how they do in the backoffice.

**Comment by hregis** [comment]
@eldy ready to test in dolistore

**Comment by eldy** [comment]
Si on saisi un description trop longue et qu'on soumet, on a bien le message, par contre, on perd toute sa saisie. Peux-tu voir pour:
- soit afficher le warning au moment du click sur le bouton submit en javascript, 
- soit reprendre la valeur du post pour préremplir si défini après affichage du warning pour ne pas tout perdre ?

**Comment by hregis** [comment]
@eldy j'ai corrigé, tu vois aussi le message lors de la saisie si tu dépasses les 400 non ?

**Comment by tiaris** [comment]
Salut à tous,

Oui Régis on voit le message. Pour la langue allemande, 400 caractères 
c'est assez court, car les mots en allemand sont facilement longs 
(pourquoi twitter n'est pas très apprécié et utilisé en Allemagne )

@+

**Comment by hregis** [comment]
on a pas idée d'utiliser des mots si long ! ;-)
j'ai fait en sorte de prendre en compte la valeur définie dans "Taille maximale de la description courte" qui se trouve dans "Préférences -> Produits" du backoffice de Prestashop au cas où...

**Comment by tiaris** [comment]
C'était juste un retour.

**Comment by hregis** [comment]
@tiaris et je te remercie, ainsi on a la possibilité d'augmenter cette valeur
