### ISSUE TITLE
On dolistore module submission, add a checkbox "I would like to have my module included in dolibarr core as soon as possible"

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#16]
The checkbox is off by default.
Value must be saved somewhere into database (if possible into an existing prestashop field)
Also a more complete text should be visible on a help tooltip to say
"Because a dolibarr module is a derivative work of dolibarr, a module must be licensed under a license compatible with dolibarr gpl v3 license. This means your source code could be reused to enhance dolibarr itself. However, "could" does not mean "will". So if you really want this to happen, just check this box so core team will be informed. This will not guarantee it will be done but increase seriously probability. If this is done, this will mean the module will then be maintained by dolibarr developer community, and module will be disabled from dolistore as soon as dolibarr version including it is publicaly available".

**Comment by hregis** [comment]
@eldy work in progress...

**Comment by hregis** [comment]
@eldy Ready to test in Dolistore
