### ISSUE TITLE
Add a checkbox with help to invite module editor to create a wiki page

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#17]
Checkbox can say
"I am aware that dolibarr foundation recommand me to add a page dedicated to my module on the wiki.dolibarr.org visible on
http://wiki.dolibarr.org/index.php/Category:Complementary_modules
This increase visibility of my module and may increase sell if it is a payed module"

"

**Comment by hregis** [comment]
@eldy work in progress...

**Comment by hregis** [comment]
@eldy Ready to test in Dolistore
