### ISSUE TITLE
On forum, add a button "Subject resolved"

### ISSUE THREAD

**Issue by aspangaro** [Dolibarr/dolibarr-foundation#19]
On the forum, add a button "Subject resolved" to clarify the discussion who are finished.

**Comment by BebZ** [comment]
yes, and when the question / solution is quite clear ad useful : 
a button "to add to F/A/Q" or "tips & tricks"
and "added to F/A/Q."
Another way to engage more the simple "forumers"

**Comment by jtraulle** [comment]
This is now solved with the new forums.
