### ISSUE TITLE
 Add in product/catalogue list a column to know "new module to active ?" 

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr-foundation#20]

**Comment by eldy** [comment]
When someone add a new module, we must be able to see and filter module that was "never validated".
When a module was enabled and disabled later, we must be able to make difference between a module "never validated" (so we have to enable it) and disabled manually (module is deprecated or canceled)

**Comment by eldy** [comment]
Note: It may be a date of first submission. Never mind, we need something to find from backoffice, all modules that you must "enabled" (without being annoying by old modules that were disabled voluntarily)

**Comment by hregis** [comment]
@eldy Ready to test in Dolistore

**Comment by eldy** [comment]
@hregis how can i find list of new module that need to be validated ? Is it a filter on list of product or a dedicated list ?
It seems it is managed with a date of validation, but how can we filter to get "not yet validated".

**Comment by hregis** [comment]
@eldy go to products list in backoffice, you have a column "Date add", you can filter by date, if a module has been added there is less than a month and it is not active you get this instead of the date of adding: "New to active Module". 

next you have the column "Request include core" that defines if the person wants its module is included in the dolibarr core.

**Comment by hregis** [comment]
@eldy i see for send an email when a new module is added

**Comment by eldy** [comment]
Don't waste your time with email. We want to reduce admin email. We already have too much emails for administrative tasks.
A feature to filter and see new module never activated on a scren is what we are looking for. We can go on screen when we want without beeing annoying by emails.
I still don't understand the way it works.
If module was voluntary disabled after one month, what will be the field ?
And if module was volontary not activated during the month, what will be visible value in list ?
