### ISSUE TITLE
On module submition in DoliStore, check module can work in custom directory, if no reject module submition

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr-foundation#21]

**Comment by eldy** [comment]
Currently the submission of a module unzip the fles. Tool must also parse each .php files and check that header are using the correct rules to work correctly:
- must use at least 2 includes to try to include the main.inc.php
- must use dol_include_once('/mymodule...) to include files of the module
- must use include_once DOL_DOCUMENT_ROOT.'/...' for files that are not from the module

**Comment by hregis** [comment]
@eldy 
je me prend la tête !
vérifier chaque fichier est très compliqué !

je propose plutôt de rajouter un fichier XML à la racine du module permettant de définir tout un tas d'informations, un peu comme les modules prestashop.

le développeur atteste que les informations sont corrects,
si il s'avère que les informations fournies ne correspondent pas au vrai fonctionnement, le module est désactivé !

```
<?xml version="1.0" encoding="UTF-8" ?>
<module>
    <name>multicompany</name>
    <displayName><![CDATA[MultiCompany]]></displayName>
    <version><![CDATA[3.8.3]]></version>
    <description><![CDATA[Multi-Company Management]]></description>
    <author><![CDATA[iNodbox]]></author>
    <is_multicompany>1</is_multicompany>
    <is_custom>1</is_custom>
</module>
```

**Comment by eldy** [comment]
Non, la seule manière d'avoir un controle rigoureux et d'analyser le code. 
Demander à l'auteur de mettre un fichier pour dire que son code est bon ne nous intéresse pas.
Pourquoi es-ce compliqué. Le fichier est dézippé, tu peux utilisé la fonction dolibarr qui renvoi la liste des fichier récursif du zip dézippé dans un tableau. et une simple boucle qui charge le fichier avec un preg sur le contenu pour vérifier doit etre suffisant.

**Comment by hregis** [comment]
oui mais il y a moultes façon d'inclure des classes en étant compatible custom, si je teste tous les fichiers php ça risque de prendre du temps pour certains modules ! ;-) tu ne crois pas ?

**Comment by eldy** [comment]
non je ne pense pas, un module fait moins de 2 Mo de fichiers sources en général, donc le temps de scan doit etre équivalent au temps pour lire 2Mo (les recherches étant en mémoire, c'est instantanné)

**Comment by hregis** [comment]
ok...

est-ce qu'on accepte ces différentes manières ou juste le dol_include_once ?

```
dol_include_once('/dcloud/lib/dcloud.lib.php');
include_once dirname(__FILE__).'/lib/dropbox.lib.php';
include_once '../lib/dropbox.lib.php';
```

**Comment by eldy** [comment]
Voici l'algorithme qui peut etre utilisé pour cette tache:

Après le dézippage, faire un "dol_dir_list" pour avoir un tableau avec la liste des fichiers de type .php
Faire un boucle pour chaque élément de cette liste:
- Charger le contenu du fichier dans $filecontent par un file_get_contents
- Réaliser les tests suivants sur $filecontent
  *\* Il doit y avoir un include du main ou master, cela se trouve en cherchant la chaine /require_once._.\/(main|master).inc.php/ . Si pas trouvé, ko. Si trouvé, on recherche occurence suivante. Il doit y en avoir une 2eme (si non, cela sinifie que le custom n'est pas géré)
  *_ Boucler sur les occurences de /dol_include_once([\"\'](.*)\// . Pour chaque cas trouvé, $1 doit etre égal au nom du module. Si non ko.
  *\* Cherche les occurences des /(require|include)_once((.*))/. Si $1 contient DOL_DOCUMENT_ROOT alors, il ne doit pas contenir le nom du module.

Cet algo rend les 3 écritures suivantes valides

dol_include_once('/dcloud/lib/dcloud.lib.php');
include_once dirname(**FILE**).'/lib/dropbox.lib.php';
include_once '../lib/dropbox.lib.php';

et invalide les écritures suivantes:

dol_include_once('/unrepducore/unfichier');
include_once DOL_DOCUMENT_ROOT.'/cloud/lib/dcloud.lib.php';

**Comment by hregis** [comment]
@eldy Work in progress...

**Comment by hregis** [comment]
@eldy Ready to test in Dolistore

**Comment by hregis** [comment]
Nouvelle règle de nommage des fichiers:

Module NON Dolibarr, exemple : modulePrestashop_monmodule-x.x.x.zip

Module pour Dolibarr :
- si votre répertoire de module est à la racine du zip, le nom du répertoire doit correspondre à ce qu'il y a en gras (les underscores ne sont plus permis dans le nom du répertoire) :

> module_**monmodule**-xxx.zip 
> module_**mon-module**-xxx.zip 
> module_**monmodule**_non_pris_en_compte-xxx.zip 
> module_**mon-module-fr**_non_pris_en_compte-xxx.zip 
- si votre répertoire de module est sous "htdocs" dans le zip, vous pouvez toujours utiliser les underscores dans le nom.

à voir si htdocs est toujours utile et imposer le nom du module à la racine ?
