### ISSUE TITLE
[Dolistore] Insane default number of days in module publication

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr-foundation#23]
I believe that the envisioned value was 365 (aka 1 year) but it's currently set to 3650 (aka 10 years).

**Comment by hregis** [comment]
@rdoursenaud 
j'ai mis 365 par défaut et ajouté la possibilité de modifier cette valeur dans la configuration du module blockmysales

**Comment by rdoursenaud** [comment]
Thanks :+1:

Just because I'm curious: do you know how and when new versions are deployed to dolistore.com ?

**Comment by hregis** [comment]
je te la fait en français ;-)
j'ai une copie de dolistore sur mes serveurs pour le développement, une fois que tout est testé j'envoi les modifications sur le dolistore.com et je teste à nouveau, si ok j'envoi les commits sur la branche develop.
Donc si tu vois de nouveaux commits ca veut dire que c'est mis à jour sur dolistore.

**Comment by rdoursenaud** [comment]
Non, parce que j'ai toujours 3650 jours par défaut :/

**Comment by hregis** [comment]
sur les produits déjà existant il faut modifier la valeur, mais sur une création j'ai bien 365 !

**Comment by rdoursenaud** [comment]
Exact, au temps pour moi !
