### ISSUE TITLE
Create dolibarr_box_gr.png

### ISSUE THREAD

**Issue by ndrosis** [Dolibarr/dolibarr-foundation#3]
![dolibarr_box_gr](https://cloud.githubusercontent.com/assets/4933899/7672276/e7fea050-fcf4-11e4-8095-02ee863f1561.png)

**Comment by eldy** [comment]
Can't you make a Push Request to add file into repository ?

**Comment by ndrosis** [comment]
Yes see here https://github.com/DolibarrFoundation/foundation/pull/4
