### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by toni-mx** [Dolibarr/dolibarr-foundation#39]
Hello, my name is Antonio (Toni) and we use in our company dolibarr since a couple of years ago. Looking around the wiki i found your Report board meeting of May 2021 and your Dolibarr Academy site.
I am very interested in the idea and actually planning to do something similar in smaller scale on my company to help my users understand better Dolibarr; so I decided to reach you and volunteer to help making courses.
Since I couldn't find some contact info i ended finding this git and give it a try.

I will send copy of this message to your facebook hoping for some luck.
I also registered over https://courses.dolibarr.org if you need my email address.

Regards

 -T

**Comment by eldy** [comment]
Due to a low number of users of the online training platform, we decided to close the courses. Users seems to prefer youtube video tutorial.
