### ISSUE TITLE
intervention sheet

### ISSUE THREAD

**Issue by DATUC** [Dolibarr/dolibarr-foundation#41]
Good evening
I have this lag when creating an intervention sheet on the second page

![image](https://user-images.githubusercontent.com/26550824/200872180-06ba147a-7d49-4555-8eb5-0a7143160d58.png)

**Comment by jtraulle** [comment]
Please, open an issue in [https://github.com/Dolibarr/dolibarr,](https://github.com/Dolibarr/dolibarr,) this repo is just for the foundation activities.

**Comment by DATUC** [comment]
> Good evening I have this lag when creating an intervention sheet on the second page
> 
> ![image](https://user-images.githubusercontent.com/26550824/200872180-06ba147a-7d49-4555-8eb5-0a7143160d58.png)

realy sorry tks
