### ISSUE TITLE
 Add the possibility of having the media of the preferred partner if desired - Lack of up-to-date dolibarr brochures

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr-foundation#44]
We offer you the brochures that we have updated for the representation of Dolibarr

**Comment by mybizz-site** [comment]
Dear all Could you share the process please 🙏 CYRITECH CLOUD SEC & ***@***.***☏: +352691515908www.cyritech.comOn 26 Nov 2023, at 23:22, Laurent Magnin ***@***.***> wrote:﻿
