### ISSUE TITLE
Create a paymenr module like paybox but for Caisse d epargne (api are provided by bank)

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#7]
This will allow to accept donation directly on bank account of fundation and make accountancy easier.

**Comment by jfefe** [comment]
This module is available here : https://git.aternatik.net/dolibarr/systempay

**Comment by eldy** [comment]
Can you install it and test it on the dolibarr foundation server ?

**Comment by hregis** [comment]
@eldy Work in progress...

**Comment by BebZ** [comment]
If you have the number of your Monétique contract, it is really simple to set up... with paygreen, or else (i did it with no skills, french support on the phone at paygreen)...
Or if you dont want to use bank monetique contract you can still use @darkjeff  STRIPE payments and subscriptions (paypal like)
