### ISSUE TITLE
Sync master Dolibarr member database with other foundation tools (creation of a dedicated module syncmembers)

### ISSUE THREAD

**Issue by eldy** [Dolibarr/dolibarr-foundation#9]
When we validate a new member into dolibarr, we must create/sync member into:
- mediawiki ( insert / update into database)
- joomla
- prestashop
  according to tags and type of member, we must also set or unset correct category into prestashsop account so a user linked to a member with tag "preferred partner" is declared preferred partner in prestashop.
  also a new member will be tagged in prestashop as a member and will automatically benefit the discount for members.

Other change: when disabling a member, the linked user of member must also be disabled (this is a bug to fix in dolibarrcore)

**Comment by hregis** [comment]
@eldy for joomla and prestashop it's ok for me.

**Comment by rdoursenaud** [comment]
O_o wikipedia? You mean Dolibarr wiki, right?

**Comment by hregis** [comment]
yes ! it's the fault of the heat! ;-)
